services:
  gateway:
    build: ./gateway
    ports:
      - 5001:5000
    depends_on:
      - calc1
      - calc2
      - string
  calc1:
    build: ./calc
    expose:
      - "5000"
    depends_on:
      - db

  calc2:
    build: ./calc
    expose:
      - "5000"
    depends_on:
      - db

  string:
    build: ./string
    expose:
      - "5000"
    depends_on:
      - db
  db:
    image: redis:7-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning